import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Creates the sales + sale_items tables — a sale is recorded when the
 * cashier prints the addition (a snapshot of the order at that moment),
 * independent from the (still-local, unsynced) "Encaisser" payment step.
 * clientId is generated by the mobile app as an idempotency key so its
 * offline retry queue can safely resend the same sale without duplicating
 * it — enforced by the soft-delete-aware partial unique index below, same
 * pattern as UQ_emplacements_restaurant_name / UQ_users_phone.
 */
export class CreateSales1789760000000 implements MigrationInterface {
  name = 'CreateSales1789760000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            CREATE TABLE "sales" (
                "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
                "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
                "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
                "deletedAt" TIMESTAMP,
                "createdBy" uuid,
                "updatedBy" uuid,
                "deletedBy" uuid,
                "restaurant_id" uuid NOT NULL,
                "client_id" character varying NOT NULL,
                "table_id" uuid,
                "table_label" character varying NOT NULL,
                "server_name" character varying,
                "total" integer NOT NULL,
                "printed_at" TIMESTAMP NOT NULL,
                CONSTRAINT "PK_sales" PRIMARY KEY ("id")
            )
        `);
    await queryRunner.query(`
            ALTER TABLE "sales"
            ADD CONSTRAINT "FK_sales_restaurant" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION
        `);
    await queryRunner.query(`
            ALTER TABLE "sales"
            ADD CONSTRAINT "FK_sales_table" FOREIGN KEY ("table_id") REFERENCES "tables"("id") ON DELETE SET NULL ON UPDATE NO ACTION
        `);
    await queryRunner.query(`
            CREATE UNIQUE INDEX "UQ_sales_restaurant_client" ON "sales" ("restaurant_id", "client_id") WHERE "deletedAt" IS NULL
        `);

    await queryRunner.query(`
            CREATE TABLE "sale_items" (
                "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
                "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
                "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
                "deletedAt" TIMESTAMP,
                "createdBy" uuid,
                "updatedBy" uuid,
                "deletedBy" uuid,
                "sale_id" uuid NOT NULL,
                "menu_item_id" uuid,
                "name" character varying NOT NULL,
                "unit_price" integer NOT NULL,
                "quantity" integer NOT NULL,
                CONSTRAINT "PK_sale_items" PRIMARY KEY ("id")
            )
        `);
    await queryRunner.query(`
            ALTER TABLE "sale_items"
            ADD CONSTRAINT "FK_sale_items_sale" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            ALTER TABLE "sale_items" DROP CONSTRAINT "FK_sale_items_sale"
        `);
    await queryRunner.query(`
            DROP TABLE "sale_items"
        `);
    await queryRunner.query(`
            DROP INDEX "UQ_sales_restaurant_client"
        `);
    await queryRunner.query(`
            ALTER TABLE "sales" DROP CONSTRAINT "FK_sales_table"
        `);
    await queryRunner.query(`
            ALTER TABLE "sales" DROP CONSTRAINT "FK_sales_restaurant"
        `);
    await queryRunner.query(`
            DROP TABLE "sales"
        `);
  }
}
