import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  ArrayMinSize,
  IsArray,
  IsISO8601,
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUUID,
  Min,
  ValidateNested,
} from 'class-validator';
import { CreateSaleItemDto } from './create-sale-item.dto';

export class CreateSaleDto {
  @ApiProperty({
    description:
      'Idempotency key generated by the mobile app — retrying the same sale (e.g. after an ' +
      'offline queue retry) with the same clientId never creates a duplicate.',
    example: 'sale-3fa85f64-1732012345678000',
  })
  @IsNotEmpty()
  @IsString()
  clientId: string;

  @ApiPropertyOptional({ description: 'Table ID this sale was printed for' })
  @IsOptional()
  @IsUUID()
  tableId?: string;

  @ApiProperty({ description: 'Table label, snapshotted at print time', example: '4' })
  @IsNotEmpty()
  @IsString()
  tableLabel: string;

  @ApiPropertyOptional({ description: 'Server/cashier name, snapshotted at print time' })
  @IsOptional()
  @IsString()
  serverName?: string;

  @ApiProperty({ description: 'Total amount (FCFA)', example: 23000 })
  @IsInt()
  @Min(0)
  total: number;

  @ApiProperty({ description: 'When the ticket was printed on the device (ISO 8601)' })
  @IsISO8601()
  printedAt: string;

  @ApiProperty({ type: [CreateSaleItemDto] })
  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => CreateSaleItemDto)
  items: CreateSaleItemDto[];
}
